(function($){'use strict';if($.fn.owlCarousel){$(".welcome_slides").owlCarousel({items:1,margin:0,loop:!0,nav:!0,navText:['<i class="icofont icofont-swoosh-left"></i>','<i class="icofont icofont-swoosh-right"></i>'],dots:!1,autoplay:!0,autoplayTimeout:7000,smartSpeed:500,autoplayHoverPause:!1})}
var owl=$('.welcome_slides');owl.owlCarousel();owl.on('translate.owl.carousel',function(event){$('.owl-item .single_slide .welcome_text_area h2').removeClass('animated').hide();$('.owl-item .single_slide .welcome_text_area p').removeClass('animated').hide();$('.owl-item .single_slide .welcome_text_area .btn').removeClass('animated').hide()})
owl.on('translated.owl.carousel',function(event){$('.owl-item.active .single_slide .welcome_text_area h2').addClass('animated custom_slideInUp').show();$('.owl-item.active .single_slide .welcome_text_area p').addClass('animated custom_slideInUp_2').show();$('.owl-item.active .single_slide .welcome_text_area .btn').addClass('animated custom_slideInUp_btn_1').show()})
if($.fn.owlCarousel){$(".testimonials").owlCarousel({items:2,margin:30,loop:!0,nav:!1,dots:!0,autoplay:!0,smartSpeed:500,responsive:{0:{items:1},992:{items:1}}})}
if($.fn.owlCarousel){$(".app_screenshots").owlCarousel({items:5,margin:30,loop:!0,nav:!0,navText:['<i class="icofont icofont-swoosh-left"></i>','<i class="icofont icofont-swoosh-right"></i>'],center:!0,dots:!1,autoplay:!0,smartSpeed:500,responsive:{0:{items:1},768:{items:3},992:{items:5}}})}
if($.fn.meanmenu){$('.main_menu_area .mainmenu nav').meanmenu({onePage:!0})}
if($.fn.onePageNav){$('#nav').onePageNav({currentClass:'current_page_item',changeHash:!1,scrollSpeed:1500,scrollThreshold:0.5,filter:'',easing:'linear',begin:function(){},end:function(){},scrollChange:function($currentListItem){}})}
$('.video_btn').magnificPopup({disableOn:0,type:'iframe',mainClass:'mfp-fade',removalDelay:160,preloader:!0,fixedContentPos:!1});$.scrollUp({scrollName:'scrollUp',scrollDistance:450,scrollFrom:'top',scrollSpeed:500,easingType:'linear',animation:'fade',animationSpeed:200,scrollTrigger:!1,scrollTarget:!1,scrollText:'<i class="icofont icofont-long-arrow-up"></i>',scrollTitle:!1,scrollImg:!1,activeOverlay:!1,zIndex:2147483647});if($.fn.matchHeight){$('.item').matchHeight()}
if($.fn.mb_YTPlayer){$('.player').mb_YTPlayer()}
new WOW().init();$("a[href='#']").on('click',function($){$.preventDefault()});$('.single_benifits').on('mouseenter',function(){$('.single_benifits').removeClass('active');$(this).addClass('active')});$('.counter').counterUp({delay:10,time:1500});$(window).on('scroll',function(){if($(window).scrollTop()>300){$('.main_header_area').addClass('sticky slideInDown');$('body').addClass('mobile_menu_on')}else{$('.main_header_area').removeClass('sticky slideInDown');$('body').removeClass('mobile_menu_on')}});$(window).on('load',function(){$('body').css('overflow-y','visible');$('#preloader').fadeOut('slow',function(){$(this).remove()});$('.fulltext').hide();$('.readmore').click(function(event){event.preventDefault();$(this).parent().find('.fulltext').slideToggle('slow');$(this).parent().toggleClass('show_more');$(this).text($(this).text()=='Read less...'?'Read more...':'Read less...')})})})(jQuery)